---

- name: Install nginx
  apt: 
    name: nginx
    state: present
  tags: nginx

- name: create www directory
  file:
    path: /var/www/html/wordpress/public_html
    state: directory
    mode: '0755'
  tags: nginx

- name: Copy nginx conf file for a wordpress
  template: 
    src: default.conf
    dest: /etc/nginx/sites-available/wordpress.conf
    mode: '0755'
  tags: nginx

- name: rm default symlink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
  tags: nginx
  
- name: create a new symlink
  file:
    src: /etc/nginx/sites-available/wordpress.conf
    dest: /etc/nginx/sites-enabled/wordpress.conf
    state: link
  notify: restart nginx
  tags: nginx